### PR TITLE
Fix #87

### LINKED ISSUE #87: this._map._renderer is undefined
I'm using the latest version of Leaflet and the Canvas renderer. I've copied the code from the docs.

Please help! :)

### PR DESCRIPTION
**Pull request by t-sch**
map._renderer was undefined if using panes

### CODE REVIEW

**Comment by jayli3n** [comment]
Amazing, looks like a dupe of this PR tho:
https://github.com/makinacorpus/Leaflet.TextPath/pull/85

**Comment by t-sch** [comment]
Oh, didn't see. Should have been merged for a while then...

**Comment by babastienne** [comment]
It is indeed a duplicate. I'll close the other merge request and we'll review this one soon.

Thanks for your contribution. :pray:

**Comment by jayli3n** [comment]
Thanks, for me, i've tested and it fixed error that came up when using latest leaflet with panes etc.

**Review by mabhub — APPROVED** [review]
LGTM

**Pull request merged**
