### PR TITLE
Add character-level rotate support

### PR DESCRIPTION
**Pull request by hanfeisun**
A possible solution for this issue:
https://github.com/makinacorpus/Leaflet.TextPath/issues/30

Demo can be previewed at:
http://hanfeisun.github.io/Leaflet.TextPath/

### CODE REVIEW

**Comment by leplatrem** [comment]
This is great ! Thank you !

Would you mind adding a mention in the readme to expose the feature ?

**Comment by leplatrem** [comment]
Thanks !

@fredericbonifas from my side, it looks ok to merge

**Comment by leplatrem** [comment]
I hadn't seen that @kirkau had implemented something similar. Maybe we can merge both into one ``rotate`` option.

The solution is different though :)

**Comment by fredericbonifas** [comment]
Thanks for this PR. I don't know yet how to name this option as a `rotate` option is already available. For now, you proposal can be implemented using the `attributes` option:

```json
attributes: {
    "style": "writing-mode: tb-rl; glyph-orientation-vertical: 180;"
}
```

**Comment by hanfeisun** [comment]
@fredericbonifas  I agree it can be implemented in the attribute, but that may look a bit intricate.  There is no `rotate` option currently but only an option called `orientation`, which is "word-level rotate" instead of "character-level rotate"..

**Comment by mabhub** [comment]
Rotation of text is now possible through `orientation` [option](https://github.com/makinacorpus/Leaflet.TextPath#options).

Please share any additional comments you may have.

**Pull request closed without merging**
